version: '3.8'  # Optional: You can remove this line if you get the obsolete warning

services:
  frontend:
    build:
      context: ./frontend  # Path to frontend folder
      dockerfile: Dockerfile.frontend  # Reference to the frontend Dockerfile
    ports:
      - "3000:3000"  # Exposes port 3000 for the frontend
  
  backend:
    build:
      context: ./backend  # Path to the backend folder
      dockerfile: Dockerfile.backend  # Reference to the backend Dockerfile
    ports:
      - "3001:3001"  # Exposes port 3001 for the backend
    volumes:
      - ./backend:/app  # Optional: Sync your local backend files with the container
    environment:
      - NODE_ENV=production  # Optional: Set environment variables
