# Use a node image as the base
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json first to install dependencies
COPY package*.json /app/

# Install dependencies
RUN npm install

# Now, copy the rest of the application files after installing dependencies
COPY . /app/

# Expose port 3001 for the backend
EXPOSE 3001

# Start the backend server with server.js
CMD ["node", "src/server.js"]

